spring:
  datasource:
    url: jdbc:mysql://localhost/sampledb
    username: root
    password: Htaka1qazxsw2
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:develop-resources/schema.sql
      data-locations: classpath:develop-resources/data.sql